services:
  - type: web
    name: recommender-api
    env: python
    plan: free
    pythonVersion: 3.10.13
    buildCommand: bash render-build.sh
    startCommand: poetry run uvicorn src.api.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: MODEL_DIR
        value: models
      - key: USE_FAISS
        value: "1"
      - key: FAISS_GPU
        value: "0"
